name: github pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Publish
        run: dotnet publish PlanningListFilterer.sln -c:Release -o:publish -p:GHPages=true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish/wwwroot
          force_orphan: true
